# Generated by Django 2.1.5 on 2019-01-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
                ('housing', models.CharField(choices=[('VILLA', 'villa'), ('APT', 'appartment')], default='VILLA', max_length=5)),
                ('floor_nbr', models.CharField(max_length=64, null=True)),
                ('counpound_name', models.CharField(max_length=64, null=True)),
                ('apt_villa_nbr', models.IntegerField(null=True)),
                ('details', models.CharField(max_length=512, null=True)),
                ('coordonates', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('payment_reference', models.CharField(max_length=64, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('str', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.CharField(choices=[('AM', 'from 4:00 a.m. to 6:00 a.m.'), ('NOON', 'from 11:00 a.m. to 12:00 p.m.'), ('PM', 'from 15:00 p.m. to 16:00 p.m.')], default='AM', max_length=4)),
                ('reception_type', models.CharField(choices=[('R', 'ring the bell'), ('L', 'let in the front door')], default='L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
