# Generated by Django 2.1.5 on 2019-01-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, unique_for_date='date'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='orders.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preference', to='orders.Preference'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_item',
            field=models.ManyToManyField(blank=True, related_name='ordered_item', through='orders.OrderItem', to='orders.Item'),
        ),
    ]
