# Generated by Django 2.1.5 on 2019-02-06 06:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190130_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='coordonates',
        ),
        migrations.AddField(
            model_name='address',
            name='json_geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
