# Generated by Django 2.1.5 on 2019-02-06 06:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190206_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='json_geocode',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
