# Generated by Django 2.1.7 on 2019-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190214_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='counpound_name',
            new_name='counpound_building_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='floor_nbr',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='reception_type',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='delivery_choice',
            field=models.CharField(choices=[('4:00 - 7:00', 'from 4:00 a.m. to 7:00 a.m.'), ('10:30 - 11:30', 'from 10:30 a.m. to 11:30 a.m.'), ('18:00 - 20:00', 'from 18:00 p.m. to 20:00 p.m.')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='reception_choice',
            field=models.CharField(choices=[('ring the bell', 'ring the bell'), ('let in the front door', 'front door')], default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='housing',
            field=models.CharField(choices=[('Villa', 'villa'), ('Appartment', 'appartment')], default='VILLA', max_length=5),
        ),
    ]
