# Generated by Django 2.1.7 on 2019-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190324_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='str',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
