# Generated by Django 2.1.7 on 2019-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_default_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='AO_activated',
            field=models.BooleanField(default=False),
        ),
    ]
