# Generated by Django 2.1.7 on 2019-03-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_ao_order_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='order',
            new_name='orders',
        ),
    ]
